services:
  - type: web
    name: titan-global-fx
    env: python
   buildCommand: |
  apt-get update && apt-get install -y \
    gcc \
    python3-dev \
    libjpeg-dev \
    zlib1g-dev \
    libpng-dev \
    libwebp-dev \
    libtiff-dev \
    libfreetype6-dev \
    liblcms2-dev \
    libopenjp2-7-dev \
    libharfbuzz-dev \
    libfribidi-dev \
  && pip install -r requirements.txt \
  && python manage.py collectstatic --noinput \
  && python manage.py migrate \
  && echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('titanfx', 'titanfx@gmail.com', 'titan123') if not User.objects.filter(username='titanfx').exists() else None" | python manage.py shell
